### ISSUE TITLE
requirements for training the model

### ISSUE THREAD

**Issue by 20050710212** [y-kawagu/dcase2020_task2_baseline#2]
Hi, Yohei, it is a fantastic work. Can I ask some questions about the requirements for training the model.
1. What is the least requirements for a pc? My pc has a memory of 8G, and 1050Ti (4G GPU memory). Even though I changed the batch_size to 1, it still ran out of memory. From my experience, my pc could train the model with only 267k parameters. 
2. My pc can not run the model according to the '**requirements.txt**'. I did the following changes then it works. I have no idea whether it is common or only for me. I hope this will help.
**Keras-Preprocessing==1.1.0**
**gast==0.3.3** (It always reminds me that gast==0.3.3 is imcompatible with tensorflow==1.15.)

**Comment by y-kawagu** [comment]
Thank you very much!

1. Minimum requirements for a PC
I am sorry. I have not checked it exactly.
We will confirm it at the beginning of the week.

2. About "requirements.txt"
We will also check it at the beginning of the week.
As soon as we get information, we will report you.

**Comment by nakamura419** [comment]
Thank you very much.
I want to know your environment.
1. OS version
2. Python version
	 
For answering the second question, I changed versions to
- Keras-Preprocessing == 1.1.0
- gast == 0.3.3
and ran the baseline.
The same results were obtained.

**Comment by 20050710212** [comment]
@nakamura419 
Thanks for your reply.
I run the code in 
Windows10 Home (version 1903), 
Pycharm 2019.2.4(Community),
Python 3.6.10.

**Comment by Yuki-Nikaido** [comment]
Answer questions 1.
As a result of training only with the largest amount of data, Toy Car, the maximum memory usage was 7578MB.
Even if batch_size was changed, this usage did not change much, so I think it is better not to use all dev_data with 8GB memory.

**Comment by Yuki-Nikaido** [comment]
We have found that the memory usage can be reduced to 4136MB if the parameter of "n_mels" is changed from 128 to 64.
Please try it.

**Comment by 20050710212** [comment]
@Yuki-Nikaido
Thank you. I changed the **'n_mels'** from 128 to 64, and **'batch_size'** from 512 to 1, it still does not work. However, I reduced half of the training data, then it works. For example, there are 3291 files in **valve**. The training process works when only 1496 files are used.

**Comment by 20050710212** [comment]
Because **train_data = list_to_vector_array()** read all data in to **train_data**, it is very memory-consuming. It could save memory consumption by reading data in batch_size.

**Comment by Yuki-Nikaido** [comment]
If only one model (ToyCar, valve ... etc) is trained, it can be executed with 8GB memory, so if you use all data, how about training only one model in one execution?
When using n_mels = 64 and using all dev_data, it was confirmed that a maximum of 8527 MB of memory was used, so in an 8 GB memory environment, training using all dev_data would be difficult.
(Maximum memory usage depends on garbage collection)

**Comment by y-kawagu** [comment]
@20050710212 Thank you very much!
We understand that loading data little by little will save memory consumption.
However, processing speed will be slower. So, we will not revise this repository in such a direction.
At this time, it is recommended to train one machine-type model at a time as @Yuki-Nikaido said.
We hope you understand.

**Comment by 20050710212** [comment]
@y-kawagu @Yuki-Nikaido @nakamura419 
Thank you for the reply. I have already add a memory chip in my pc.
