### ISSUE TITLE
eroor

### ISSUE THREAD

**Issue by arunodhayan** [y-kawagu/dcase2020_task2_baseline#3]
I tried using the convolution2D and LSTM autoencoder so made this change to split the input layer 

model = keras_model.get_model(param["feature"]["n_mels"] ,param["feature"]["frames"]) so I will have input as (128,5,1) 1-is channel 

but I get this error 
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (1360000, 640)

**Comment by y-kawagu** [comment]
I can not know your detail implement, so I imagine it. 
If you use a convolution2D, LSTM, or your other network, of course you must fit the dimensions of input data suitable for your network.
According to the error message, there is a gap between the input vector and your networks.
So I recommend you should check and fix this gap.

**Comment by arunodhayan** [comment]
should i need to change anything here

train_data = list_to_vector_array(files,
                                          msg="generate train_dataset",
                                          n_mels=param["feature"]["n_mels"],
                                          frames=param["feature"]["frames"],
                                          n_fft=param["feature"]["n_fft"],
                                          hop_length=param["feature"]["hop_length"],
                                          power=param["feature"]["power"])

**Comment by arunodhayan** [comment]
dims = n_mels , frames (did this change (128,5))

    # 02 generate melspectrogram using librosa
    y, sr = file_load(file_name)
    mel_spectrogram = librosa.feature.melspectrogram(y=y,
                                                     sr=sr,
                                                     n_fft=n_fft,
                                                     hop_length=hop_length,
                                                     n_mels=n_mels,
                                                     power=power)

    # 03 convert melspectrogram to log mel energy
    log_mel_spectrogram = 20.0 / power * numpy.log10(mel_spectrogram + sys.float_info.epsilon)

    # 04 calculate total vector size
    vector_array_size = len(log_mel_spectrogram[0, :]) - frames + 1

    # 05 skip too short clips
    if vector_array_size < 1:
        return numpy.empty((0, dims[0],dims[1])) -- did this change 

    # 06 generate feature vectors by concatenating multiframes
    vector_array = numpy.zeros((vector_array_size, dims[0],dims[1]))
    for t in range(frames):
        vector_array[:, n_mels * t: n_mels * (t + 1),frames*t:frames*(t+1)] = log_mel_spectrogram[:, t: t + vector_array_size].T   (added this frames *t, frames * (t+1))  but bit confused with log_mel_spectrogram what to add for third dimension

**Comment by arunodhayan** [comment]
vector_array_size = len(log_mel_spectrogram[0, :]) - frames + 1
    
    # 05 skip too short clips
    if vector_array_size < 1:
        return numpy.empty((0, dims[0],dim[1]))

    # 06 generate feature vectors by concatenating multiframes
    vector_array = numpy.zeros((vector_array_size, dims[0],dims[1]))
    print (vector_array)
    for t in range(frames):
        vector_array[:, n_mels * t: n_mels * (t + 1)] = log_mel_spectrogram[:, t: t + vector_array_size].T

**Comment by y-kawagu** [comment]
Hi.
I cannot catch up with your idea completely.
At least, in your code, "dataset[vector_array.shape[0] * idx: vector_array.shape[0] * (idx + 1), :]" seems to be wrong because the "dataset" has 3 dimensions.
The "vector_array[:, n_mels * t: n_mels * (t + 1)]" in your code seems to be wrong due to a similar mistake.

**Comment by arunodhayan** [comment]
i had reshaped the training data 

train_data=numpy.reshape(train_data,(train_data.shape[0],param["feature"]["n_mels"], param["feature"]["frames"],1))

**Comment by arunodhayan** [comment]
should i try to change the vector dimensions during feature extraction or after feature extraction before sending the train data should I reshape

**Comment by y-kawagu** [comment]
How is the dimensions of the "train_data"?

**Comment by y-kawagu** [comment]
before reshape

**Comment by arunodhayan** [comment]
train data dimensions now is (train_data.shape[0], n_mels,frames,1)

**Comment by y-kawagu** [comment]
Then, have you checked the reshaped vectors (image) visually?

**Comment by y-kawagu** [comment]
Then, how shape is the input layer? 
Is it be the same to "(train_data.shape[0],128,5,1)"?

**Comment by arunodhayan** [comment]
yes it is the same (train_data.shape[0],128,5,1)"

**Comment by arunodhayan** [comment]
is it possible that i can reduce the frame no 4 ??

**Comment by y-kawagu** [comment]
Please see the error message.
"ValueError: Error when checking target: expected conv2d_7 to have shape (128, 8, 1) but got array with shape (128, 5, 1)"
I guess that the loss function is the error between input (128, 5, 1) and output (128, 8, 1), isn't it?

**Comment by arunodhayan** [comment]
i had changed the loss to categorical_cross entropy
at the last layer of the decoder error  

ValueError: Error when checking target: expected conv2d_15 to have shape (128, 4, 1) but got array with shape (128, 5, 1)

**Comment by y-kawagu** [comment]
Why categorical cross entropy????
I can not understand your idea but I guess that your "decoder error" means a function like an error between the input vector and the output vector. If so, the size of the output layer must be the same to the input layer. However, the size of the output layer is not the same to the input layer in your implementation.
Please pay attention to pooling (shrinking size) and upsampling (stretching size).

**Comment by arunodhayan** [comment]
is it possible to upsample from even to an odd no like 2 to 5  
eg my shape is None, 64, 2, 16  to 128,5,1

**Comment by y-kawagu** [comment]
I don't know how. Can't you use an odd number for input?

**Comment by y-kawagu** [comment]
> I don't know how. Can't you use an odd number for input?

Sorry mistake. 
Can't you use an !!!even!!! number for input?

**Comment by arunodhayan** [comment]
Yes is did I reduced the frame size to 4 so now the dimensions I'll be ( train_data.shape[0],128,4,1)

**Comment by Yuki-Nikaido** [comment]
Thank you for your question.

I'm closing this issue. Please feel free to make a new one if something else happens.
