### ISSUE TITLE
shape error 

### ISSUE THREAD

**Issue by arunodhayan** [y-kawagu/dcase2020_task2_baseline#4]
============== MODEL TRAINING ==============

          Layer (type)                 Output Shape              Param #   

         input_1 (InputLayer)         (None, 128, 5, 1)         0         

        conv2d_1 (Conv2D)            (None, 128, 5, 32)        320       

        max_pooling2d_1 (MaxPooling2 (None, 64, 3, 32)         0         

        conv2d_2 (Conv2D)            (None, 64, 3, 16)         4624      

        max_pooling2d_2 (MaxPooling2 (None, 32, 2, 16)         0         
       
        conv2d_3 (Conv2D)            (None, 32, 2, 8)          1160      
 
        max_pooling2d_3 (MaxPooling2 (None, 16, 1, 8)          0         
 
        conv2d_4 (Conv2D)            (None, 16, 1, 8)          584       
 
        up_sampling2d_1 (UpSampling2 (None, 32, 2, 8)          0         
 
        conv2d_5 (Conv2D)            (None, 32, 2, 16)         1168      
 
        up_sampling2d_2 (UpSampling2 (None, 64, 4, 16)         0         
  
         conv2d_6 (Conv2D)            (None, 64, 4, 32)         4640      
 
         up_sampling2d_3 (UpSampling2 (None, 128, 8, 32)        0         
 
         conv2d_7 (Conv2D)            (None, 128, 8, 1)         33        
 

Total params: 12,529
 Trainable params: 12,529
 Non-trainable params: 0
 _________________________________________________________________
Traceback (most recent call last):
  File "00_train.py", line 211, in <module>
    verbose=param["fit"]["verbose"])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected conv2d_7 to have shape (128, 8, 1) but got array with shape (128, 5, 1)

**Comment by y-kawagu** [comment]
Probably the above is an additional information for the other issue (#3 ), isn't it?
Please see the answer for it.
